[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "osep"
version = "0.0.1"
dependencies = [
  "pycryptodome",
  "pefile",
  "pylnk3"
]
requires-python = ">=3.8"
authors = [
  { name="Exil", email="yassine.settai@gmail.com" }
]
description = "Tradecraft for Offensive Security PEN-300 (OSEP)"
readme = "README.md"
license = "MIT"

[project.scripts]
craft = "osep:main"

[tool.setuptools]
py-modules = ["osep"]
packages = ["tradecraft"]
include-package-data = true

[tool.setuptools.package-data]
tradecraft = ["bin/*", "templates/**/*", "ssl/*"]  